# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e80662b66283218b2e6d5028820f6b86b2cb33619012d0d1d81ab00913391b7bf335cd592579306303dfb554f619356e5816ab9e4b358b867496084fceb8cb58

test:
  secret_key_base: 948fe1b10de4b2825a08bf3f3f05c55cd49a7f096bf22b7db260c4bf72401306c009cf21678664ea31d9bedef5006bc392d24b6246b5cf778c8156a97dd59486

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
